export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';

export const GET_CART_TOTAL = 'GET_CART_TOTAL';

export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';

export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';

export const CLEAR_ITEM = 'CLEAR_ITEM';

